import React from "react";
import {
  Upload,
  Brain,
  UserCheck,
  HeartPulse,
  ShieldCheck,
  Clock,
  FileText,
  Heart,
} from "lucide-react";
import { cn } from "../../lib/utils"; // Assuming you have this utility file from the example

// Your existing features data
const features = [
  {
    title: "Secure Document Upload",
    description:
      "Patients can safely upload their medical records and health reports with full privacy.",
    icon: <Upload size={24} />,
  },
  {
    title: "AI-Assisted Analysis",
    description:
      "Our AI scans your health data and generates preliminary suggestions for doctors to review.",
    icon: <Brain size={24} />,
  },
  {
    title: "Doctor Validation",
    description:
      "Qualified doctors review and validate AI-generated prescriptions and recommendations.",
    icon: <UserCheck size={24} />,
  },
  {
    title: "Health Tracking",
    description:
      "Track your blood pressure, medications, and treatment adherence over time for better outcomes.",
    icon: <HeartPulse size={24} />,
  },
  {
    title: "Privacy & Security",
    description:
      "All health records and personal data are encrypted and protected to ensure full confidentiality.",
    icon: <ShieldCheck size={24} />,
  },
  {
    title: "24/7 Support",
    description:
      "Patients and doctors have access to support anytime for queries or guidance.",
    icon: <Clock size={24} />,
  },
  {
    title: "Detailed Reports",
    description:
      "Receive comprehensive prescription and treatment reports generated by AI and verified by doctors.",
    icon: <FileText size={24} />,
  },
  {
    title: "Patient Wellness",
    description:
      "Empowering patients to take control of their health with insights, reminders, and care tracking.",
    icon: <Heart size={24} />,
  },
];

export default function FeaturesSectionDemo() {
  return (
    <section className="bg-[#121212] dark:bg-neutral-950 py-20 px-4 md:px-10">
      <div className="max-w-7xl mx-auto text-center mb-16">
        <h2 className="text-3xl md:text-5xl font-bold text-white mb-4">
          Features
        </h2>
        <p className="text-neutral-300 text-base md:text-lg max-w-2xl mx-auto">
          Discover the powerful tools and capabilities that make our platform the best
          choice for managing your healthcare journey.
        </p>
      </div>

      {/* Grid container inspired by your example, with added top/bottom borders */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 relative z-10 max-w-7xl mx-auto border-t border-b border-neutral-800">
        {features.map((feature, index) => (
          <Feature key={feature.title} {...feature} index={index} />
        ))}
      </div>
    </section>
  );
}

// New Feature component, structured like your example
const Feature = ({ title, description, icon, index }) => {
  return (
    <div
      className={cn(
        "flex flex-col lg:border-r py-10 relative group/feature border-neutral-800",
        // Logic to add left border for the first item in each row
        (index === 0 || index === 4) && "lg:border-l border-neutral-800",
        // Logic to add bottom border for the top row
        index < 4 && "lg:border-b border-neutral-800"
      )}
    >
      {/* Top row hover gradient */}
      {index < 4 && (
        <div className="opacity-0 group-hover/feature:opacity-100 transition duration-200 absolute inset-0 h-full w-full bg-gradient-to-t from-neutral-800 to-transparent pointer-events-none" />
      )}
      {/* Bottom row hover gradient */}
      {index >= 4 && (
        <div className="opacity-0 group-hover/feature:opacity-100 transition duration-200 absolute inset-0 h-full w-full bg-gradient-to-b from-neutral-800 to-transparent pointer-events-none" />
      )}

      {/* Your styled icon */}
      <div className="mb-5 relative z-10 px-10">
        <div
          className="h-12 w-12 rounded-full bg-blue-900/30 flex items-center 
                         justify-center text-blue-400"
        >
          {icon}
        </div>
      </div>

      {/* Animated title from your example */}
      <div className="text-lg font-bold mb-2 relative z-10 px-10">
        <div className="absolute left-0 inset-y-0 h-6 group-hover/feature:h-8 w-1 rounded-tr-full rounded-br-full bg-neutral-700 group-hover/feature:bg-blue-500 transition-all duration-200 origin-center" />
        <span className="group-hover/feature:translate-x-2 transition duration-200 inline-block text-white">
          {title}
        </span>
      </div>

      {/* Description text */}
      <p className="text-sm text-neutral-400 max-w-xs relative z-10 px-10">
        {description}
      </p>
    </div>
  );
};