import React from "react";
import Navbar from "../components/Navbar";
import Spline from "@splinetool/react-spline";
import { Timeline } from "../components/ui/timeline";
import FeaturesSectionDemo from "../components/ui/features"; // Ensure default export
import { InfiniteMovingCards } from "../components/ui/infinite-moving-cards";
import Footer from "../components/Footer";

// Timeline data with fragments instead of <p> to avoid nested <p> issues
const timelineData = [
  {
    title: "Upload Documents",
    content: (
      <>
        User uploads medical records, reports, and relevant health documents securely
        to the platform for AI analysis.
      </>
    ),
  },
  {
    title: "AI Review",
    content: (
      <>
        AI scans the uploaded documents and generates preliminary suggestions and
        prescriptions based on user health data and context.
      </>
    ),
  },
  {
    title: "Prescription Report",
    content: (
      <>
        A detailed prescription report is generated by AI, including medications,
        dosage, and treatment recommendations.
      </>
    ),
  },
  {
    title: "Doctor Validation",
    content: (
      <>
        The generated prescription is reviewed and validated by a qualified doctor
        through the doctor supervision interface.
      </>
    ),
  },
  {
    title: "User Data Sharing",
    content: (
      <>
        Once approved, the prescription and relevant health insights are securely
        shared with the user and stored in the medical history.
      </>
    ),
  },
  {
    title: "Follow-Up & Tracking",
    content: (
      <>
        Users can continuously track their blood pressure and treatment adherence
        over time for improved health outcomes.
      </>
    ),
  },
];

const cardData = [
  {
    name: "Anjali Sharma",
    title: "Patient",
    quote: "This platform helped me track my blood pressure and understand my medication better. My doctor approved all AI recommendations.",
  },
  {
    name: "Rohit Verma",
    title: "Patient",
    quote: "I could upload my reports online and get reliable suggestions without going to the clinic repeatedly.",
  },
  {
    name: "Dr. Meena Rao",
    title: "Doctor",
    quote: "The AI-generated reports save time, and the validation interface ensures safety for all patients.",
  },
  {
    name: "Priya Singh",
    title: "Patient",
    quote: "Tracking my BP over months has never been easier. The AI and doctor supervision combo gave me confidence in my treatment.",
  },
];


export default function CommonDashboard() {
  return (
    <>
      <Navbar />

      {/* Hero Section */}
      <div className="h-screen w-full bg-black">
        <Spline scene="https://prod.spline.design/KHbqYuRbUz8oZsP5/scene.splinecode" />
      </div>

      
      {/* <section className="h-screen bg-[#121212] text-white flex flex-col items-center justify-center text-center">
        <h1 className="text-5xl font-bold mb-4">About Us</h1>
        <p className="text-lg text-gray-300 max-w-2xl">
          We are passionate creators building next-gen AI and web experiences.
        </p>
      </section> */}

      {/* Timeline Section */}
      <Timeline data={timelineData} />

      {/* Features Section */}
      <FeaturesSectionDemo />

      
      <InfiniteMovingCards items={cardData} />
      <Footer/>
    </>
  );
}